sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t romanpavlushchenko/docker-react -f Dockerfile.dev .


# commands to run the test suite or do anything else
script:
  - docker run -e CI=true romanpavlushchenko/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-1-413373933883"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY